server:
  port: 5000
  
spring:
  datasource:
    url: jdbc:postgresql://lily-spyglass.cluster-c4eqo06kg56i.us-east-1.rds.amazonaws.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_PROD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            
#frontend-url: http://lily-spyglass.s3-website-us-east-1.amazonaws.com
frontend-url: http://d1ulkr0tra4x6n.cloudfront.net
mode: prod
s3-bucket-name: lily-spyglass-images
aws-access-key: ${IMAGE_BUCKET_ACCESS_KEY}
aws-secret-key: ${IMAGE_BUCKET_SECRET_KEY}