server:
  port: 5000
  
spring:
  datasource:
    url: jdbc:postgresql://lily-spyglass.cluster-c4eqo06kg56i.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 137424696014-062cnpkc3rkfsihr5fiauaf637nf5l3r.apps.googleusercontent.com
            client-secret: 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
            
frontend-url: http://lily-spyglass.s3-website-us-east-1.amazonaws.com