server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spyglass
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_DEV}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
            
frontend-url: http://localhost:5173